# .github/workflows/sync.yml
name: Rebase Upstream
on:
  schedule:
  - cron: "0 0 * * *"  # run everyday
  workflow_dispatch:    # run manually

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
        ref: master

    - uses: imba-tjd/rebase-upstream-action@master
      with:  # all args are optional
        upstream: openwrt/openwrt
        branch: master
        depth: 0
